name: norbu_timer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logging: ^1.0.1
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  awesome_notifications: ^0.0.5+8
  background_fetch: ^0.7.2
  font_awesome_flutter: ^8.8.1
  progressive_image: ^1.0.1
  palette_generator: ^0.2.3
  flutter_statusbarcolor: ^0.2.3
  shared_preferences: ^2.0.6
  datetime_picker_formfield: ^2.0.0
  get_it: ^4.0.4
  easy_debounce: ^2.0.0
  audioplayers: ^0.19.0
  flutter_ringtone_player: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  #firebase_messaging: ^9.1.1
  #firebase_core: ^1.0.3
  url_launcher: ^5.7.5
  http: ^0.13.1
  path_provider: ^2.0.2
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/res_app_icon.png"
  adaptive_icon_background: "assets/icons/res_app_icon.png"
  adaptive_icon_foreground: "assets/icons/res_app_icon.png"    

flutter:

  uses-material-design: true
  assets:
    - assets/res_rhy_bre_sound3_hold.mp3
    - assets/res_rhy_bre_sound1_emp.mp3
    - assets/res_rhy_bre_sound2_inh.mp3
  
#dependency_overrides:
#  platform: ^3.1.0

